"use client";

import EventPhasePage from "../components/EventPhasePage";
import { useSiteLanguage } from "../components/siteLanguage";

export default function DuringEventPage() {
  const { language } = useSiteLanguage();
  const copy = {
    th: {
      back: "à¸à¸¥à¸±à¸š",
      phase: "Phase 02",
      title: "à¸£à¸°à¸«à¸§à¹ˆà¸²à¸‡à¸‡à¸²à¸™",
      summary:
        "Turn live event activity into visible carbon intelligence. Show emissions in real time and help attendees understand their impact while they participate.",
      steps: [
        "Display live emissions data on venue screens and interactive touchpoints.",
        "Attendees use LINE OA to understand emissions generated by their participation.",
        "Connect live activity with offset options and engagement prompts during the event.",
      ],
      stats: [
        { label: "Live refresh", value: "24h" },
        { label: "Touchpoints", value: "8+" },
        { label: "Engagement", value: "64%" },
      ],
    },
    en: {
      back: "Back",
      phase: "Phase 02",
      title: "During-Event",
      summary:
        "Turn live event activity into visible carbon intelligence. Show emissions in real time and help attendees understand their impact while they participate.",
      steps: [
        "Display live emissions data on venue screens and interactive touchpoints.",
        "Attendees use LINE OA to understand emissions generated by their participation.",
        "Connect live activity with offset options and engagement prompts during the event.",
      ],
      stats: [
        { label: "Live refresh", value: "24h" },
        { label: "Touchpoints", value: "8+" },
        { label: "Engagement", value: "64%" },
      ],
    },
  }[language];

  return (
    <EventPhasePage
      accent="#67e8f9"
      backLabel={copy.back}
      image="/VEKIN Resource all Product/VEKIN 1/during_event.png"
      imageAlt="During-event interactive touch screen experience"
      phase={copy.phase}
      stats={copy.stats}
      steps={copy.steps}
      summary={copy.summary}
      title={copy.title}
    />
  );
}
