"use client";

import Link from "next/link";
import Header from "../components/Header";
import { useSiteLanguage } from "../components/siteLanguage";

export default function DuringEventPage() {
  const { language } = useSiteLanguage();
  const copy = {
    th: {
      back: "กลับ",
      title: "ระหว่างงาน",
      body1: "การแสดงหน้าจอค่าการปล่อยก๊าซ",
      body2: "ผู้เข้าร่วมงานสามารถใช้งานผ่านระบบ line OA\nเพื่อรับรู้การปล่อยก๊าซและชดเชยการปล่อยที่เกิดจากการเข้าร่วมงาน"
    },
    en: {
      back: "Back",
      title: "During-Event",
      body1: "Display emissions data on screen",
      body2: "Attendees can use LINE OA\nto understand emissions and offset what is generated by attending the event"
    }
  }[language];

  return (
    <main className="relative min-h-screen overflow-hidden bg-black text-white">
      <Header />
      {/* FULL-BLEED BACKGROUND INFRASTRUCTURE */}
      <img
        src="/VEKIN Resource all Product/VEKIN 1/during_event.png"
        alt="During-event interactive touch screen experience"
        className="absolute inset-0 h-full w-full object-cover select-none pointer-events-none"
      />
      
      {/* RESPONSIVE READABILITY LAYERS - Boosts text legibility across narrow screens */}
      <div className="absolute inset-0 bg-black/35 md:bg-transparent z-10 pointer-events-none" />
      <div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/30 to-black/45 z-10 pointer-events-none" />
      <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/40 to-transparent z-10 pointer-events-none" />

      {/* DYNAMICALLY POSITIONED RETURN ANCHOR */}
      <Link
        href="/"
        className="absolute left-4 top-4 sm:left-6 sm:top-6 z-30 rounded-full border border-white/20 bg-black/40 px-4 py-2.5 text-xs sm:text-sm font-bold backdrop-blur-lg transition-all duration-300 hover:border-white/50 active:scale-95"
      >
        ‹ {copy.back}
      </Link>

      {/* HERO CONTENT ARCHITECTURE */}
      <section className="relative z-20 flex min-h-screen items-end px-5 pb-12 pt-24 sm:px-12 lg:px-[7vw] lg:pb-[12vh]">
        <div className="max-w-[820px] w-full text-left">
          
          {/* MAIN HEADLINE COMPONENT */}
          <h1 className="text-[clamp(2.4rem,7.5vw,5.2rem)] font-black leading-[1.1] tracking-tight text-white">
            {copy.title}
          </h1>
          
          {/* CLEANLY HANGING RE-INDENTED LIST COMPONENT */}
          <div className="mt-6 sm:mt-10 space-y-4 text-[clamp(1.05rem,2.5vw,1.65rem)] font-bold sm:font-black leading-relaxed sm:leading-[1.4] text-white/90">
            <div className="flex items-start gap-2.5 pl-4 -indent-4">
              <span className="text-emerald-400 select-none">•</span>
              <p>{copy.body1}</p>
            </div>
            <div className="flex items-start gap-2.5 pl-4 -indent-4">
              <span className="text-emerald-400 select-none">•</span>
              <p className="whitespace-pre-line">{copy.body2}</p>
            </div>
          </div>

        </div>
      </section>
    </main>
  );
}