import React from "react";

import { pageMetadata } from "../seo";
import PhaseClient from "./PhaseClient";

export const metadata = pageMetadata({
  title: "During-Event Carbon Tracking",
  description:
    "Display live emissions data on venue screens and interactive touchpoints, while attendees use LINE OA to understand the emissions generated by their participation.",
  path: "/during-event"
});

export default function Page() {
  return <PhaseClient />;
}
