"use client";

import EventPhasePage from "../components/EventPhasePage";
import { useSiteLanguage } from "../components/siteLanguage";

export default function PhaseClient() {
  const { language } = useSiteLanguage();
  const copy = {
    th: {
      back: "กลับ",
      phase: "Phase 02",
      title: "ระหว่างงาน",
      summary:
        "เปลี่ยนกิจกรรมที่เกิดขึ้นระหว่างงานให้เป็นข้อมูลคาร์บอนที่มองเห็นได้ แสดงการปล่อยคาร์บอนแบบเรียลไทม์ และช่วยให้ผู้เข้าร่วมเข้าใจผลกระทบของตนเองในระหว่างที่ร่วมงาน",
      steps: [
        "แสดงข้อมูลการปล่อยคาร์บอนแบบเรียลไทม์บนจอภายในงานและจุดสัมผัสแบบอินเทอร์แอกทีฟ",
        "ผู้เข้าร่วมใช้ LINE OA เพื่อทำความเข้าใจการปล่อยคาร์บอนที่เกิดจากการเข้าร่วมของตน",
        "เชื่อมโยงกิจกรรมสดเข้ากับตัวเลือกการชดเชยคาร์บอนและการมีส่วนร่วมระหว่างงาน",
      ],
      stats: [
        { label: "อัปเดตสด", value: "24h" },
        { label: "จุดสัมผัส", value: "8+" },
        { label: "การมีส่วนร่วม", value: "64%" },
      ],
    },
    en: {
      back: "Back",
      phase: "Phase 02",
      title: "During-Event",
      summary:
        "Turn live event activity into visible carbon intelligence. Show emissions in real time and help attendees understand their impact while they participate.",
      steps: [
        "Display live emissions data on venue screens and interactive touchpoints.",
        "Attendees use LINE OA to understand emissions generated by their participation.",
        "Connect live activity with offset options and engagement prompts during the event.",
      ],
      stats: [
        { label: "Live refresh", value: "24h" },
        { label: "Touchpoints", value: "8+" },
        { label: "Engagement", value: "64%" },
      ],
    },
  }[language];

  return (
    <EventPhasePage
      accent="#67e8f9"
      backLabel={copy.back}
      image="/VEKIN Resource all Product/VEKIN 1/during_event.png"
      imageAlt="During-event interactive touch screen experience"
      phase={copy.phase}
      stats={copy.stats}
      steps={copy.steps}
      summary={copy.summary}
      title={copy.title}
    />
  );
}
